on: push
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    
    
    - name: Sync files
      uses: Shary81/testing@v1.0
      with:
        server: ftp.warmprospect.com
        username: warmprospect
        password: D{G*GS$RN}0y

    - name: Get latest code
      uses: actions/checkout@v2.3.2